name: "copyrights"

on:
  push:

jobs:
  update-copyrights:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: true

      - name: Get deno version
        id: get_deno_version
        run: |
          echo "dvmrc=$(cat .dvmrc)" >> "$GITHUB_OUTPUT"

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ steps.get_deno_version.outputs.dvmrc }}"

      - name: Update
        run: "deno task copyrights"
      
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push changes
        run: |
          git add .
          git commit -m "fix: update copyrights"
          git push
        

